#pragma once
#include <pebble.h>
	
#if defined(PBL_PLATFORM_APLITE)
  #define WIDTH 			(144)
  #define HEIGHT 			(168)
  #define HEIGHT_OFFSET		(-5)
#elif defined(PBL_PLATFORM_BASALT)
  #define WIDTH 			(144)
  #define HEIGHT 			(168)
  #define HEIGHT_OFFSET		(-5)
#elif defined(PBL_PLATFORM_CHALK)
  #define WIDTH 			(180)
  #define HEIGHT 			(180)
#elif defined(PBL_PLATFORM_DIORITE)
  #define WIDTH 			(144)
  #define HEIGHT 			(168)
  #define HEIGHT_OFFSET		(-5)
#elif defined(PBL_PLATFORM_EMERY)
  #define WIDTH 			(200)
  #define HEIGHT 			(228)
  #define HEIGHT_OFFSET		(10)
#endif

#define ICON_SIZE			(39)

#if defined(PBL_RECT)
  #define TIME_FRAME     					(GRect(0, HEIGHT_OFFSET, WIDTH, 57))
  #define DATE_FRAME     					(GRect(0, HEIGHT_OFFSET+(HEIGHT*0.3), WIDTH, 32))
  #define TIME_FRAME_LOWER					(GRect(0, HEIGHT_OFFSET+(ICON_SIZE/3)+5, WIDTH, 57))
  #define DATE_FRAME_LOWER					(GRect(0, HEIGHT_OFFSET+(HEIGHT*0.3)+(ICON_SIZE/3*2), WIDTH, 32))
  #define WEATHER_FRAME     				(GRect(0, 0, WIDTH, ICON_SIZE))
  #define PHONE_LEVEL_INDICATOR_FRAME		(GRect(0, 1, ICON_SIZE, ICON_SIZE-1))
  #define PEBBLE_LEVEL_INDICATOR_FRAME		(GRect(WIDTH-ICON_SIZE, 1, ICON_SIZE, ICON_SIZE-1))
  #define NOTIF_FRAME      					(GRect(0, ICON_SIZE, WIDTH, 2*ICON_SIZE))

  #define NOTIF_ROOT_FRAME_0				(GRect(0, HEIGHT-ICON_SIZE, WIDTH, (3*ICON_SIZE)))
  #define NOTIF_ROOT_FRAME_4				(GRect(0, HEIGHT-(2*ICON_SIZE), WIDTH, (3*ICON_SIZE)))
  #define NOTIF_ROOT_FRAME_8				(GRect(0, HEIGHT-(3*ICON_SIZE), WIDTH, (3*ICON_SIZE)))

#else
  #define TIME_FRAME     					(GRect(0, 5, WIDTH, 50))
  #define TIME_FRAME_LOWER					TIME_FRAME
  #define NOTIF_ROOT_FRAME_0				(GRect(0, 55, WIDTH, (2*ICON_SIZE)-5))
  #define WEATHER_FRAME     				(GRect(0, 0, WIDTH, ICON_SIZE))
  #define EXTRA_NOTIF_FRAME_0				(GRect(0, 55+ICON_SIZE-5-20, WIDTH, ICON_SIZE+20))
  #define EXTRA_NOTIF_FRAME_8				(GRect(0, 55+(2*ICON_SIZE)-5, WIDTH, ICON_SIZE+20))
  #define PHONE_LEVEL_INDICATOR_FRAME		(GRect(4, 1, ICON_SIZE, ICON_SIZE-1))
  #define PEBBLE_LEVEL_INDICATOR_FRAME		(GRect(WIDTH-ICON_SIZE-4, 1, ICON_SIZE, ICON_SIZE-1))
  #define NOTIF_FRAME      					(GRect(0, ICON_SIZE-5, WIDTH, ICON_SIZE))
  #define DATE_FRAME     					(GRect(0, 55+(2*ICON_SIZE), WIDTH, HEIGHT-(55+(2*ICON_SIZE))))
  #define DATE_FRAME_LOWER					DATE_FRAME
#endif

#define ICON_OFFSET		(28)

#define NUMBER_OF_ICONS		(8)

#define DEBUG_PEBBLE_PERCENT   (90)
#define DEBUG_PHONE_PERCENT    (68)

typedef struct {
	BitmapLayer *layer;
	GBitmap *bitmap;
	int number;
	GRect position;
} TemplateIcon;

typedef struct {
	Layer *layer;
	GRect start;
	GRect finish;
} LayerAnimationData;

enum Watchface {
  WATCHFACE_0, 
  WATCHFACE_4,
  WATCHFACE_8,
};

enum WeatherService {
	WEATHER_YAHOO = 0,
	WEATHER_OPEN_WEATHER_MAP = 1,
	WEATHER_DARK_SKY = 2
};

enum HubKey {
  HUB1_ACCOUNT_KEY = 0,
  HUB2_ACCOUNT_KEY = 1,
  HUB3_ACCOUNT_KEY = 2,
  HUB4_ACCOUNT_KEY = 3,
  HUB5_ACCOUNT_KEY = 4,
  HUB6_ACCOUNT_KEY = 5,
  HUB7_ACCOUNT_KEY = 6,
  HUB8_ACCOUNT_KEY = 7,

  USE_ANIMATION_KEY = 10,
  VIBRATE_ON_DISCONNECT_KEY = 11,
  VIBRATE_KEY = 12,
  PHONE_PERCENT = 13,

  SLOT_COUNTER_KEY = 15,

  COLOR_TIME_BACKGROUND = 17,
  COLOR_NOTIFICATION_TEXT = 18,

  COLOR_NOTIFICATION_BACKGROUND = 20,


  COLOR_TIME_TEXT = 23,
  
	

  NUMBER_OF_SLOTS = 27,
  TEMPERATURE_SCALE = 28,
  WEATHER_ICON = 50,
  WEATHER_TEMP = 51,
  WEATHER_REQUEST = 52,
  WEATHER_CITY = 53,
  WEATHER_ERROR = 54,
  WEATHER_SERVICE = 55,
  WEATHER_API = 56,
  BATTERY_LEVEL_FORMAT = 60,
  JS_IS_READY = 99,
  ASK_NOTIF2WATCH_REFRESH = 100
};

static uint32_t ALL_ICONS_34[] = {
  RESOURCE_ID_CLEAR_DAY_34,               // 0
  RESOURCE_ID_CLEAR_NIGHT_34,             // 1
  RESOURCE_ID_CLOUD_ERROR_34,             // 2
  RESOURCE_ID_CLOUDY_34,                  // 3
  RESOURCE_ID_COLD_34,                    // 4
  RESOURCE_ID_DRIZZLE_34,                 // 5
  RESOURCE_ID_FOG_34,                     // 6
  RESOURCE_ID_HOT_34,                     // 7
  RESOURCE_ID_NOT_AVAILABLE_34,           // 8
  RESOURCE_ID_PARTLY_CLOUDY_DAY_34,       // 9
  RESOURCE_ID_PARTLY_CLOUDY_NIGHT_34,     // 10
  RESOURCE_ID_PHONE_ERROR_34,             // 11
  RESOURCE_ID_RAIN_34,                    // 12
  RESOURCE_ID_RAIN_SLEET_34,              // 13
  RESOURCE_ID_RAIN_SNOW_34,               // 14
  RESOURCE_ID_SLEET_34,                   // 15
  RESOURCE_ID_SNOW_34,                    // 16
  RESOURCE_ID_SNOW_SLEET_34,              // 17
  RESOURCE_ID_THUNDER_34,                 // 18
  RESOURCE_ID_WIND_34,                    // 19
  RESOURCE_ID_ICON_BBM_34,                // 20
  RESOURCE_ID_ICON_CALL_34,               // 21
  RESOURCE_ID_ICON_EMAIL_34,              // 22
  RESOURCE_ID_ICON_FACEBOOK_34,           // 23
  RESOURCE_ID_ICON_LINKEDIN_34,           // 24
  RESOURCE_ID_ICON_NOTIFICATION_34,       // 25
  RESOURCE_ID_ICON_PIN_34,                // 26
  RESOURCE_ID_ICON_TEXT_34,               // 27
  RESOURCE_ID_ICON_TWITTER_34,            // 28
  RESOURCE_ID_ICON_VOICEMAIL_34,          // 29
  RESOURCE_ID_ICON_WHATSAPP_34,           // 30
  RESOURCE_ID_ICON_EMPTY_34,              // 31
  RESOURCE_ID_ICON_BLAQ_34,               // 32
  RESOURCE_ID_ICON_SLACK_34,              // 33
  RESOURCE_ID_ICON_INSTAGRAM_34,          // 34
  RESOURCE_ID_ICON_QUICKPOST_34,          // 35
  RESOURCE_ID_ICON_TWITTLY_34,            // 36
  RESOURCE_ID_ICON_WECHAT_34,             // 37
  RESOURCE_ID_ICON_HG10_34,               // 38
  RESOURCE_ID_ICON_GOOGLE_TALK_34,        // 39
  RESOURCE_ID_ICON_CALENDAR_34,           // 40
  RESOURCE_ID_ICON_VIP_34,                // 41
  RESOURCE_ID_ICON_FOURSQUARE_34,         // 42
  RESOURCE_ID_ICON_FACE10_34,             // 43
  RESOURCE_ID_ICON_JUST10_34,             // 44
  RESOURCE_ID_ICON_VK10_34,               // 45
  RESOURCE_ID_ICON_MESSENGER_34,          // 46
  RESOURCE_ID_ICON_GOOGLE_PLAY_34,        // 47
  RESOURCE_ID_ICON_NOTIF2WATCH_34,        // 48
  RESOURCE_ID_ICON_HUB_34,                // 49
  RESOURCE_ID_ICON_SKYPE_34,              // 50
  RESOURCE_ID_ICON_GMAIL_34,              // 51
  RESOURCE_ID_ICON_SCREENSHOT_34,         // 52
  RESOURCE_ID_ICON_YOUTUBE_34,            // 53
  RESOURCE_ID_ICON_TELEGRAM_34,           // 54
  RESOURCE_ID_ICON_DISCORD_34,            // 55
  RESOURCE_ID_ICON_PUSHBULLET_34,         // 56
  RESOURCE_ID_ICON_LINE_34,               // 57
  RESOURCE_ID_ICON_BADOO_34,              // 58
  RESOURCE_ID_ICON_BOX_34,                // 59
  RESOURCE_ID_ICON_CHROME_DOWNLOAD_34,    // 60
  RESOURCE_ID_ICON_DROPBOX_34,            // 61
  RESOURCE_ID_ICON_FIVERR_34,             // 62
  RESOURCE_ID_ICON_GOOGLE_PLUS_34,        // 63
  RESOURCE_ID_ICON_MEETUP_34,             // 64
  RESOURCE_ID_ICON_ONEDRIVE_34,           // 65
  RESOURCE_ID_ICON_PAYPAL_34,             // 66
  RESOURCE_ID_ICON_PERISCOPE_34,          // 67
  RESOURCE_ID_ICON_PINTEREST_34,          // 68
  RESOURCE_ID_ICON_SNAPCHAT_34,           // 69
  RESOURCE_ID_ICON_TINDER_34,             // 70
  RESOURCE_ID_ICON_TUMBLR_34,             // 71
  RESOURCE_ID_ICON_VIBER_34,              // 72
  RESOURCE_ID_ICON_VINE_34,               // 73
  RESOURCE_ID_ICON_GRINDR_34,             // 74
  RESOURCE_ID_ICON_GOOGLE_PHOTOS_34,      // 75
  RESOURCE_ID_ICON_DELIVERIES_34,         // 76
  RESOURCE_ID_ICON_TETHERING_34,          // 77
  RESOURCE_ID_ICON_GOOGLE_DRIVE_34,       // 78
  RESOURCE_ID_ICON_ANDROID_34,            // 79
  RESOURCE_ID_ICON_GOOGLE_KEEP_34,        // 80
  RESOURCE_ID_ICON_EUROSPORT_34,          // 81
  RESOURCE_ID_ICON_LE_MONDE_34,           // 82
  RESOURCE_ID_ICON_THREEMA_34,            // 83
  RESOURCE_ID_ICON_SZDE_34,               // 84
  RESOURCE_ID_ICON_DB_NAVIGATOR_34,       // 85
  RESOURCE_ID_ICON_RUNNER_34,             // 86
  RESOURCE_ID_ICON_MUSIC_34,              // 87
  RESOURCE_ID_ICON_GOOGLE_ALLO_34,        // 88
  RESOURCE_ID_ICON_DASHBOARD_34,          // 89
  RESOURCE_ID_ICON_SIGNAL_34,             // 90
};
